server:
  port: 19991
  servlet:
    context-path: /alzheimer

# 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.167.4:3306/alzheimer?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: yy@2020AL
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    mongodb:
      host: 123.56.167.4    #mongo服务IP
      port: 27017            #mongo服务端口号
      database: admin       #mongo数据库名
      username: admin
      password: yy@2020AL

  mail:
    host: smtp.qq.com  # 发送方电子邮箱服务器，如果是163就是stmp.163.com
    username: XXXXXX@qq.com #发送方邮箱
    password: XXXXXXX # 如果是QQ邮箱，就是发送方授权码
  # 通过验证
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*.xml
  # pojo类所在包路径
  type-aliases-package: com.space.alzheimer.dao




logging:
  config: classpath:conf/log4j2.xml


